# This is a basic workflow to help you get started with Actions

name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello mate!"
      - name: Print goodbye
        run: echo "Done - bye"
